on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make some test files
        run: |
          mkdir test
          echo "testing" > test/test_file1.md
          echo "testing" > test/test_file2.md

      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: test/*

      - name: Make some more test files
        run: |
          mkdir docs
          echo "testing" > docs/docs_file1.md
          echo "testing" > docs/docs_file2.md

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/*

      - name: Make ugly naming test files
        run: |
          mkdir xyz
          echo "testing-xzy" > xyz/xyz_file1.md
          echo "testing-xzy" > xyz/xyz_file2.md

      - uses: actions/upload-artifact@v3
        with:
          name: ttt
          path: xyz/*

  test_all:
    runs-on: ubuntu-latest

    needs:
      - build
      
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -al 
      - run: ls -al test
      - run: ls -al docs
      - run: ls -al ttt
      - run: ls -al xyz

  test:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test

      - uses: actions/download-artifact@v3
        with:
          name: docs

      - uses: actions/download-artifact@v3
        with:
          name: ttt

      - run: ls -al
